"""first

Revision ID: df576181b014
Revises: 
Create Date: 2022-12-10 03:59:34.423625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df576181b014'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'loc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('loc', mysql.VARCHAR(length=40), nullable=False))
    # ### end Alembic commands ###
