"""scnd

Revision ID: f061904e03a1
Revises: df576181b014
Create Date: 2022-12-10 04:00:09.694056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f061904e03a1'
down_revision = 'df576181b014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('loc', sa.CHAR(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'loc')
    # ### end Alembic commands ###
